---
# (string) Timezone for the servers
# timezone: "America/New_York"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

packages:
  - hdparm
  - htop
  - intel-gpu-tools
  - ipvsadm
  # - lm_sensors
  - nano
  - nvme-cli
  - socat
  - python3-selinux
  - apparmor-utils
  # - SELinux-policy

  # TODO(ansible): Might be required for newer Intel CPU generations
  # https://ask.fedoraproject.org/t/intel-graphics-best-practices-and-settings-for-hardware-acceleration/21119
  # - intel-media-driver
  # - mesa-dri-drivers
  # - libva-intel-driver
  # - libva-intel-hybrid-driver
  # - libva-utils
  # - libva-vdpau-driver
  # - libvdpau-va-gl
