---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 172.16.11.2
    worker:
      hosts:
        k8s-1:
          ansible_host: 172.16.11.3
        k8s-2:
          ansible_host: 172.16.11.4
