# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:RuO0zpQkqwww528Vs7LLmgd2tqI=,iv:jIFUIHkwBZkhR20UsC0s3+pSssjVdSbY7JiGYZXLZzI=,tag:vbp7TV4VvXBOGqbWAM8z9Q==,type:str]
    api-key: ENC[AES256_GCM,data:tiqMrkHAaQ3VveKg625QcrDmodbr1ZPWydmS1BlyMLXX+ML+ZA==,iv:7nXAoqmMfiELwKqxPwr5NLPxvc332aNksbu7PhZx25U=,tag:09Cl3IFuysaO4F1VuaMUeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qnudj4yuejaq6p48lyymkhtlw2un3r7n5n8jfw7dswhzcxxc7p9qxnr3d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa1JTMC91VkRjR2kycHdL
            YVFxeWZab3h6SzNoNnpVbzJZbHdHYnhmM1NnCmhqbVZvanArQlZucERSUzZYSkl2
            d1NnbU1DN3ZTMDRHNXA2U1IrYWg3M2sKLS0tIFJTL0JMakEzNUJrR2hBTVlmSkdy
            eWd3L0dmMWNHRUJIQllhdFhPRS9HaE0KF92HaYKVM1s0B4tjuT96HuWwTlPtWQfQ
            qcqNvZ1ICC45AD8X2TcXtAWfasFsT/42R69RbAFWDBQzgz+ISL/tLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T01:40:39Z"
    mac: ENC[AES256_GCM,data:z+bD40fJYaSxKZoQmzKNIfJVnjN5w/Prm54LjvrWrcvxC9hfGeG2kPCVCAB62EijubcPUnD3SZBFEDtCppd0t6LNwZdkPFFekXGWoAG05Fv03Yuf+hyzZaGOPDOY69eIxseT6qTZysSESg2XgkbeQlbm6NBKH+v2nh9t00D++w0=,iv:fwVxvzjnwaWXw5mY07oUWsamiUD/jwZSh0GYVPvjhs8=,tag:naBy6weJiMuKgdcCG7dasQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
