# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:PWVvPms1ynIYYJqwp7jKTDiZnl4=,iv:r/hNmUhCoKZtYFFWAgeeT1dJsVCm5uzmopwr/6w4I18=,tag:qVgzSF+qwSfxz4iaCPjVpA==,type:str]
    api-key: ENC[AES256_GCM,data:zI5GGlQ2LGOfBUNPyUF/yq5ttJjM8YA7+yywTr2L5uUBfyuSVg==,iv:vIf+3Kf38JYbC5100QLIJIHS5Xi+QZD3w2LWaR5YgFc=,tag:TGCjn6k1bLFZdN884ulj8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qnudj4yuejaq6p48lyymkhtlw2un3r7n5n8jfw7dswhzcxxc7p9qxnr3d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TlVyQ1pwcG5oVGlVV3VX
            TmowTkJXNUwxeVYvOE8wUmZNck5abFNqWFNrCkVYZm8wc2wxVW5QK3lpYktIblNo
            V1BrQnptb1lYcnpzZ3ZZZUs3R0lxUjgKLS0tIC9lVWdocWkrRS9TVmhjZVVmUHBN
            N3ZOTE5LMVFmUmF0TmdwN1E5WWtjTnMKdPAHMyJyKprhA/j3eqy4wK2zjNrcG8oj
            CSr3NrXe/+7UhpqD9U0EoNmxp4W2cxwGeD5AXQXm08GS4jxs3RgDBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T19:03:22Z"
    mac: ENC[AES256_GCM,data:5DeJdfyhs9HpFmuZCvqLcC4oAdk4ZR76Vfc2lSDNIrxImS0YjAk0DPYQcvqKVBmNW8+Mup4fJpWPQGAoIJYuS742WcbkYE89ki7WWd7TisA9rVYnvtmQMnN3jFPnqV47AzCLxV60MizGQcWklkTI6917bfZnHPq9+bCohXCzlSg=,iv:miKlkjxXgCH/FibtoDZ3PJotkkCp+A8OAQi/StP12aw=,tag:5LzUqHir33y+XEPjIvX/kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
