# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:943rVHpZDw852U5/QSl4,iv:h/j33WopOuTYpJDQXySRGwLYaOtsqM9Vvlqu0LdQ5Og=,tag:3M0tC8ye0mZbxIobKNcnyA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:/0dYj5o2PcJjds0r7lGGsy+Aolg=,iv:3P7eebZSvQLXafKs/AhtFqqg47jfNbKb15oPhOZ1QjM=,tag:UDgXiYlgYp6pT13N96mifw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qnudj4yuejaq6p48lyymkhtlw2un3r7n5n8jfw7dswhzcxxc7p9qxnr3d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UkFqcFJsTzNQUE8yVlFq
            dTF5QmpkaEpJUS94T3M5YUQyM0lJY3pCTXpjCk5UODJCYnhjaGdpQk4zb0hZeGFH
            MWt3V29idU02YWR6RldkcjFoUG5vUTAKLS0tIFE5cW9DN01Bb2RSZEp0UXlESnU0
            TGQwcnd0K1NPNVI3dFZza3U0UXc2ajgK1bABZ3dA/wwSq0GM9aWZBDD4hjFUoLNI
            3N5dMNW0DwqmZrOkSwyGXbEhu9KxxMZvaN4W3I3v04W+8AnBA9kx0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T01:40:39Z"
    mac: ENC[AES256_GCM,data:Vz55bO3hsqBXys2ujGifoonzk1zi60REC4t19VQ/32nyJZprQQH7SjA3/DbcwC+olJebYvtAxkQK+PIlpY2bN+NirakCE4JfJ6MykaKF1frQTVB2ox7eJH74quaj7Qns6SIikZWLeFo3apl2Wq4qLNdRhgpRLKsyOKTDiizyzjk=,iv:r5Fakev/aSpCw/KgH6cVbfgEV+X9jA4kENASTUWIR80=,tag:Y5z3RudlJ2Zlwd2kt2YasA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
