---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 172.16.11.10-172.16.11.20
  METALLB_K8S_GATEWAY_ADDR: 172.16.11.10
  METALLB_INGRESS_ADDR: 172.16.11.11
