---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com:noah-guillory/home-cluster
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
