---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/noah-guillory/home-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-cluster
