kind: Secret
ansible_user: ENC[AES256_GCM,data:kCbhbw==,iv:5MqYR6/NkuchYUw3gY19tFQkQ/bMznHGaLtnc79FxlQ=,tag:7cOisFEM/VgmZj5pZUroqg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:11uMYU+JawZdrCupLg==,iv:FB4VQSAcZqPbIgd61Gwl/dT1Sxv7XAXbYOfaqm32XM4=,tag:Tbe5R+KZyX99rdhhTQnmCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qnudj4yuejaq6p48lyymkhtlw2un3r7n5n8jfw7dswhzcxxc7p9qxnr3d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod2hnZnlJajdvbXhUU3VR
            MjRSYThqUVVhbjNOY2YrMEIzU0RnYXZZb2dNCnRtWlRnRjlYNFE4RGpmV0NsYXR0
            c3hHUHFaRFpwa0JiZlJXaGpKOXFkcTgKLS0tIGh2Z2RTUlhvL1RPc2J0UG54VUR5
            T1FrZkJCaFc4NExLbkcydlJ2OExZKzAK2jn8WFI+FRayNVXCN5D4ZF8Yn+HAEd62
            sV/Ebj2sY7IlwFUF8lmbqZLwv13w0CmWiR0/FnZnOWDYHxnsav6tEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T01:40:40Z"
    mac: ENC[AES256_GCM,data:PcewiUTVoJB8L5tJ9apHPZHUn+Y3BY+LylJV9NhcCT++aJSF3p+UKsRvnXqW1/dadLMgBUScAMvBf1jeiLC9ROKAKlyHR1VUj/FMpgJgVTQQ7QBaMzovegTFNGHUZSAsI9bcjvkCQBFIzo78ANXV+fouvHKFgBRLw+7uNddhw4E=,iv:ich2DLbI9vDQTdaLt70fP8240dWt39l0uNkZQiADIkI=,tag:k8efuu/rVkEW2edc7I+bZQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
