kind: Secret
ansible_user: ENC[AES256_GCM,data:HUOsrQ==,iv:gdK7AxyUMYm0Y0w4NJfVTz+tBzza2zIElNb7K3O7TUE=,tag:Fl48xvaR8sUf1QP8/wqv7w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:a9tAyIbO+Si+k2Czkw==,iv:7++pmvQw4nGdXuMszw6bUDy0et0O4MpAeyirYvuvgi0=,tag:p+bVeseVuLdq1s6iaOlDSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qnudj4yuejaq6p48lyymkhtlw2un3r7n5n8jfw7dswhzcxxc7p9qxnr3d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MTR4c29lTThWbHF0TGh1
            T1RlZEQ5TENDaE5MdXZ2TEZvZ2QzNHNQVEdVClZRVmlLZnpuVUtBYXFnRmhmMnpk
            dURES0h5MnRpbFRPb3F0cFltbUQ3c0UKLS0tIDRGeHZlQlFCWDdFMzJGYWZRR282
            YlhVUlM0eHdhVlE3WWViRml3b3IwUnMKZHVSfNWhS2Ds5nnj4nbQcp/XLHQVhKL9
            nKjAxGueJhG/0P5SGAYc9iBkcYooTaVmY6omB9gYH8YyIBSeAOYpnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T18:45:54Z"
    mac: ENC[AES256_GCM,data:S8/Kw5jrqeQ+qyGuIm27wZ49OrVd8iEgf56tjnWFLpgMbtijoGjB5H1QotKGwZ2BfhcyMyIgm01p3VcGLJCtlMO2gqdj7YnWKmny6tMOYKMx+KjlakuZ5Qk26L2bSnDHd8sUnKpPPUOKbdVHHxK5szgQkHexPrkIJ1eED2494yY=,iv:An0UpQW/MkA1K6FV4Q7Fie8CZpQvM4OU73JWRWXlcQ0=,tag:COmErsTy5hNXFeH1qPK/7w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
