# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TLMNgR13CJsekOwI8+zZ9YRUfEEH288XALv9Ks7R2t9C+uN1Nh+7JQ==,iv:DDAS6hHj5XRyDou1kwmpEqRIpboVx/6iooZ3RJJU19I=,tag:lL4KoM6jb0Ypsmlz1pt+0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qnudj4yuejaq6p48lyymkhtlw2un3r7n5n8jfw7dswhzcxxc7p9qxnr3d3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZUxFc1VmL1kzMFByVndk
            WVlYT2xadEZ5NWY3YmdBeG1XTUFteVFvVmpjCkZMY2hSRS8vanRVcm52MWJncklE
            eHArYTBJTWtXZ0h1L3RnK25obEZmNzAKLS0tIHNtb1Q1T1BuelBIUjFFQWE0aytj
            ZnFUOHBtcVZwbnZxbEduSmVYQjdJdlUK9WLaBjRPItZV/H24qA9+Lm0AyfI1iRpv
            eltWNzXUaz9pqfiteIsckNZmeNDX+sKhRpr91k4KCVSLJPDgVfmijA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-17T19:03:22Z"
    mac: ENC[AES256_GCM,data:iORYOZJyFgDVLxkDfiOHBAF5A+vFoVQfjZP7vZ6D8Gq+z6boxQ1/VUuHzCS9gbRCCINzQdPM+ePxiiwNp8tLP4JMNQS3ildyh1myOjcpmYmQ6d3e0sLz4nxhN5PTj8jMePn5n658nNnFsZZ34DOasIGKF+ZJghBrfk/QshOY8Gk=,iv:74Xw91eWOL+f7tSs28I3e6cLduluM/MM5ehKE00LRn8=,tag:wcwJ7k/485pmZZ6EcpLl1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
